INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (1, 'Australian greyhound', 'Австралийская борзая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (2, 'Australian Hound', 'Австралийская гончая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (3, 'Australian Shepherd', 'Австралийская овчарка');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (4, 'Australian Cattle Dog', 'Австралийская пастушья собака');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (5, 'Aussie', 'Австралийский терьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (6, 'Australian Silky Terrier', 'Австралийский шелковистый терьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (7, 'Azawak', 'Азавак');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (8, 'Ainu', 'Айну');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (9, 'Akita', 'Акита');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (10, 'Alpine taksoobrazny Brakk', 'Альпийский таксообразный бракк');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (11, 'Alaskan Malamute', 'Аляскинский маламут');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (12, 'American Blue Gascon Hound', 'Американская голубая гасконская гончая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (13, 'American foxhound', 'Американская гончая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (14, 'American raccoon hound', 'Американская енотовая гончая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (15, 'American Bull Terrier', 'Американский бультерьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (16, 'American Cocker', 'Американский кокер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (17, 'American Pit Bull', 'Американский питбультерьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (18, 'American Staffordshire Terrier', 'Американский стаффордширский терьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (19, 'American harer', 'Американский харьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (20, 'Anatolian Shepherd', 'Анатолийская овчарка');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (21, 'English raccoon hound', 'Английская енотовая гончая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (22, 'English Shepherd', 'Английская овчарка');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (23, 'English Pointing', 'Английские легавые');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (24, 'English Bulldog', 'Английский бульдог');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (25, 'English Setter', 'Английский сеттер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (26, 'English Springer Spaniel', 'Английский спрингер-спаниель');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (27, 'English Toy Spaniel', 'Английский той-спаниель');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (28, 'English Toy', 'Английский тойтерьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (29, 'English Foxhound', 'Английский фоксхаунд');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (30, 'Appenzeller', 'Аппенцеллер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (31, 'Apso', 'Апсо');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (32, 'Artezian-Norman Basset', 'Артезиано-нормандский бассет');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (33, 'Artuazskaya Hound', 'Артуазская гончая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (34, 'Arezhskaya Hound', 'Арьежская гончая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (35, 'Consumption Shepherd', 'Астурийская овчарка');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (36, 'Afghan Hound', 'Афганская борзая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (37, 'African sand dog', 'Африканская песчаная собачка');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (38, 'Affen pinscher', 'Аффен-пинчер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (39, 'Bavarian Mountain Hound', 'Баварская горная гончая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (40, 'Balkan Hound', 'Балканская гончая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (41, 'Basenji', 'Басенджи');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (42, 'Basque Shepherd', 'Баскская овчарка');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (43, 'Basset', 'Бассет');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (44, 'Basset Hound', 'Бассет-хаунд');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (45, 'Bedlingtonterer', 'Бедлингтонтерьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (46, 'Alpine White Terrier', 'Белый высокогорный терьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (47, 'Belgian Shepherd', 'Бельгийская овчарка');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (48, 'Belgian Brakk', 'Бельгийский бракк');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (49, 'Berne Hound', 'Бернская гончая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (50, 'Berne Cattle Dog', 'Бернская пастушья собака');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (51, 'Beagle', 'Бигль');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (52, 'Beagle-harer', 'Бигль-харьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (53, 'Biya', 'Бийи');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (54, 'Bichon-Lyon', 'Бишон-лион');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (55, 'Bichon Vries', 'Бишон-фризе');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (56, 'Bloodhound', 'Бладхаунд');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (57, 'Bobtail', 'Бобтейл');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (58, 'Bohemian Terrier', 'Богемский терьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (59, 'Boxer', 'Боксер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (60, 'Most Anglo-French Hound', 'Большая англо-французская гончая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (61, 'Large-sentonzhskaya Gascon Hound', 'Большая гасконско-сентонжская гончая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (62, 'Great Blue Gascon Hound', 'Большая голубая гасконская гончая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (63, 'Large tree hound', 'Большая древесная гончая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (64, 'Large Spanish Hound', 'Большая испанская гончая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (65, 'Great Swiss Mountain and Cattle Dog', 'Большая швейцарская горная пастушья собака');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (66, 'Big Mountain Dog', 'Большой зенненхунд');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (67, 'Big myunsterlender', 'Большой мюнстерлендер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (68, 'Large Portuguese podengu', 'Большой португальский поденгу');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (69, 'Bongoterer', 'Бонготерьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (70, 'Border-collie', 'Бордер-колли');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (71, 'Borderterer', 'Бордертерьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (72, 'Dogue de Bordeaux', 'Бордоский дог');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (73, 'Greyhounds with erect ears', 'Борзые со стоячими ушами');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (74, 'Bearded Collie', 'Бородатая колли');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (75, 'Beauceron', 'Босерон');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (76, 'Bosnian coarse-wooled Hound', 'Боснийская грубошерстная гончая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (77, 'Boston Terrier', 'Бостонский терьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (78, 'Brundle Brakk', 'Брандл-бракк');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (79, 'Briard', 'Бриар');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (80, 'Brussels Griffon', 'Брюссельский гриффон');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (81, 'Bullmastiff', 'Бульмастиф');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (82, 'Bullterrier', 'Бультерьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (83, 'Basset Griffon Vendee', 'Вандейский бассет-гриффон');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (84, 'Velshterer', 'Вельштерьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (85, 'Hungarian sheepdog', 'Венгерская овчарка');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (86, 'Hungarian kuvach', 'Венгерский кувач');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (87, 'West Gothic Dog', 'Вестготская собака');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (182, 'Mastiff', 'Мастиф');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (88, 'Westphalian taksoobrazny Brakk', 'Вестфальский таксообразный бракк');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (89, 'Fold Greyhounds', 'Вислоухие борзые');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (90, 'Wolf Spitz', 'Волчий шпиц');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (91, 'Volpino', 'Вольпино');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (92, 'East European Shepherd', 'Восточноевропейская овчарка');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (93, 'Otter hound', 'Выдровая гончая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (94, 'Havana Bichon', 'Гаванский бишон');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (95, 'Gamiltonstevare', 'Гамильтонстеваре');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (96, 'Hanover Hound', 'Ганноверская гончая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (97, 'Gert-Pointer', 'Герта-пойнтер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (98, 'Smooth Retriever', 'Гладкошерстный ретривер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (99, 'Glen-of-imaal Terrier', 'Глен-оф-имаал-терьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (100, 'Inca Hairless Dog', 'Голая собака инков');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (101, 'Dutch Shepherd Dog', 'Голландская овчарка');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (102, 'Blue Gascony Basset', 'Голубой гасконский бассет');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (103, 'Blue Picardie epanol', 'Голубой пикардийский эпаньоль');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (104, 'Hound Plotta', 'Гончая Плотта');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (105, 'Hound Stephen', 'Гончая Стефана');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (106, 'Schiller Hound', 'Гончая Шиллера');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (107, 'Canes', 'Гончие');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (108, 'Mountain Hound', 'Горная гончая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (109, 'Hottentot dog', 'Готтентотская собака');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (110, 'Greyhound', 'Грейхаунд');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (111, 'Greek rabbit hound', 'Греческая заячья гончая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (112, 'Griffon', 'Гриффон');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (113, 'Dalmatian', 'Далматин');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (114, 'Danish Dachsbracke', 'Датская таксообразная гончая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (115, 'Danish broholmer', 'Датский брохольмер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (116, 'Dandie Dinmont Terrier', 'Денди-динмонт-терьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (117, 'Jack Russell Terrier', 'Джек-рассел-терьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (118, 'Dingo', 'Динго');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (119, 'Deerhound', 'Дирхаунд');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (120, 'Doberman', 'Доберман');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (121, 'Drever', 'Древер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (122, 'Dunker', 'Дункер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (123, 'Raccoon hound', 'Енотовая гончая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (124, 'Yellow with a black mask southern hound', 'Желтая с черной маской южная гончая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (125, 'West Siberian Laika', 'Западносибирская лайка');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (126, 'Zauerlandsky Brakk', 'Зауэрландский бракк');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (127, 'Golden Retriever', 'Золотистый ретривер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (128, 'Illyria Shepherd', 'Иллирийская овчарка');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (129, 'Irish Water Spaniel', 'Ирландский водяной спаниель');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (130, 'Irish Wolfhound', 'Ирландский волкодав');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (131, 'Irish Setter', 'Ирландский сеттер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (132, 'Irish Terrier', 'Ирландский терьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (133, 'Icelandic Sheepdog', 'Исландская овчарка');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (134, 'Spanish galgo', 'Испанский гальго');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (135, 'Spanish Mastiff', 'Испанский мастиф');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (136, 'Istrian Hound', 'Истрийская гончая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (137, 'Italian Hound', 'Итальянская гончая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (138, 'Italian whippet', 'Итальянская левретка');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (139, 'Yemthund', 'Йемтхунд');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (140, 'Yorkshirterer', 'Йоркширтерьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (141, 'Caucasian Shepherd', 'Кавказская овчарка');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (142, 'Kai', 'Кай');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (143, 'Kamchatka sled', 'Камчатская ездовая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (144, 'Kanaanskaya dog', 'Канаанская собака');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (145, 'Karelian-Finnish Laika', 'Карело-финская лайка');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (146, 'Karelian Bear Dog', 'Карельская медвежья собака');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (147, 'Dwarf crested dog', 'Карликовая хохлатая собачка');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (148, 'Miniature Pinscher', 'Карликовый пинчер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (149, 'Dwarf poodle', 'Карликовый пудель');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (150, 'Dwarf Spitz', 'Карликовый шпиц');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (151, 'Catalan Sheepdog', 'Каталонская овчарка');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (152, 'Keeshond', 'Кеесхонд');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (153, 'Kelpie', 'Келпи');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (154, 'Kernterer', 'Кернтерьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (155, 'Kerry Beagle', 'Керри-бигль');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (156, 'Kerry Blue Terrier', 'Керри-блю-терьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (157, 'Kisyu', 'Кисю');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (158, 'Chinese Shar', 'Китайский шарпей');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (159, 'Klumber Spaniel', 'Клумбер-спаниель');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (160, 'Koikerhonde', 'Коикерхондье');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (161, 'Labrador', 'Лабрадор');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (162, 'Labrador Retriever', 'Лабрадорский ретривер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (163, 'Landsir', 'Ландсир');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (164, 'Lapland spitz', 'Лапландский шпиц');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (165, 'Latvian Hound', 'Латвийская гончая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (166, 'Laufhund', 'Лауфхунд');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (167, 'Levesque', 'Левеск');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (168, 'Leyklendterer', 'Лейклендтерьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (169, 'Leonberger', 'Леонбергер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (170, 'Leopard Hound', 'Леопардовая гончая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (171, 'Leopard dog Katahuly', 'Леопардовая собака Катахулы');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (172, 'Lithuanian Hound', 'Литовская гончая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (173, 'Lhasa apso', 'Лхасский апсо');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (174, 'Lyutserner laufhund', 'Люцернер лауфхунд');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (175, 'Magyar agar', 'Мадьяр-агар');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (176, 'Low Anglo-French Hound', 'Малая англо-французская гончая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (177, 'Small Basset Griffon Vendee', 'Малый вандейский бассет-гриффон');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (178, 'Maltese', 'Мальтийская болонка');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (179, 'Manchester Terrier', 'Манчестерский терьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (180, 'Maremma', 'Маремма');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (181, 'Mastino Neapolitana', 'Мастино неаполитано');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (183, 'Miniature Pinscher', 'Миниатюрный пинчер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (184, 'Schnauzer', 'Миттельшнауцер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (185, 'Pug', 'Мопс');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (186, 'Moscow watch', 'Московская сторожевая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (187, 'Moscow Toy', 'Московский тойтерьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (188, 'Moody', 'Муди');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (189, 'Soft Coated Wheaten Terrier', 'Мягкошерстный пшеничный терьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (190, 'Neapolitan Mastiff', 'Неаполитанский мастиф');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (191, 'German coarse-wooled pointer', 'Немецкая грубошерстная легавая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (192, 'German longhaired pointer', 'Немецкая длинношерстная легавая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (193, 'German Shepherd', 'Немецкая овчарка');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (194, 'German Dog', 'Немецкий дог');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (195, 'German hunting terrier', 'Немецкий охотничий терьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (196, 'Nenets Laika olenegonnaya', 'Ненецкая оленегонная лайка');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (197, 'Novoshotlandsky Retriever', 'Новошотландский ретривер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (198, 'Norrbotten Spitz -', 'Норботтен-шпиц');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (199, 'Norwegian buhund', 'Норвежский бухунд');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (200, 'Norvichterer', 'Норвичтерьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (201, 'Norfolkterer', 'Норфолктерьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (202, 'Newfoundland', 'Ньюфаундленд');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (203, 'Oyrazir', 'Ойразир');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (204, 'Otterhaund', 'Оттерхаунд');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (205, 'Fawn Breton Basset Griffon', 'Палевый бретонский бассет-гриффон');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (206, 'Papillon and Fahlen', 'Папильон и фален');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (207, 'Pekingese', 'Пекинес');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (208, 'Peruvian Inca Orchid', 'Перуанская орхидея инков');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (209, 'Picardie Shepherd', 'Пикардийская овчарка');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (210, 'Harlequin Pinscher', 'Пинчер арлекин');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (211, 'Pyrenean mountain dog', 'Пиренейская горная собака');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (212, 'Pyrenean Shepherd', 'Пиренейская овчарка');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (213, 'Pyrenean Mastiff', 'Пиренейский мастиф');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (214, 'Pointer', 'Пойнтер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (215, 'Polish lowland sheepdog', 'Польская низинная овчарка');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (216, 'Polish podgalyanskaya Shepherd', 'Польская подгалянская овчарка');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (217, 'Portuguese Hound', 'Португальская гончая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (218, 'Portuguese Mountain Shepherd', 'Португальская горная овчарка');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (219, 'Pryamosherstny Retriever', 'Прямошерстный ретривер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (220, 'Puatven', 'Пуатвен');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (221, 'Poodle', 'Пудель');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (222, 'Poodle-Pointer', 'Пудель-пойнтер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (223, 'Bullets', 'Пули');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (224, 'Pumi', 'Пуми');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (225, 'Rastreador Brasileiro', 'Растреадор бразилейру');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (226, 'Rafeyru do Alentejo', 'Рафейру ду Алентехо');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (227, 'Ridgeback', 'Риджбек');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (228, 'Giant', 'Ризеншнауцер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (229, 'Rottweiler', 'Ротвейлер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (230, 'Romanian Shepherd', 'Румынская овчарка');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (231, 'Russian wolfhound', 'Русская борзая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (232, 'Russian color spaniel', 'Русская цветная болонка');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (233, 'Russian Spaniel', 'Русский охотничий спаниель');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (234, 'Black Russian Terrier', 'Русский черный терьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (235, 'Russian-European Laika', 'Русско-европейская лайка');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (236, 'Saluki', 'Салюки');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (237, 'Samoyed Laika', 'Самоедская лайка');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (238, 'St. Bernard', 'Сенбернар');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (239, 'Gordon Setter', 'Сеттер-гордон');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (240, 'Silihemterer', 'Силихэмтерьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (241, 'Skayterer', 'Скайтерьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (242, 'Skotchterer', 'Скотчтерьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (243, 'Slyugi', 'Слюги');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (244, 'Smolandstevare', 'Смоландстеваре');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (245, 'Central Asian Shepherd', 'Среднеазиатская овчарка');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (246, 'Staffordshire Bull Terrier', 'Стаффордширский бультерьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (247, 'Staffordshire Terrier', 'Стаффордширский терьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (248, 'Sussex Spaniel', 'Суссекс-спаниель');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (249, 'Dachshund', 'Такса');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (250, 'Tatranska Shepherd', 'Татранская овчарка');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (251, 'Khyi', 'Тибетский мастиф');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (252, 'Tibetan Spaniel', 'Тибетский спаниель');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (253, 'Tibetan Terrier', 'Тибетский терьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (254, 'Toy-poodle', 'Той-пудель');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (255, 'Tosa Inu', 'Тоса-ину');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (256, 'Whippet', 'Уиппет');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (257, 'Wales Terrier', 'Уэльский терьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (258, 'West Highland White Terrier', 'Уэст-хайленд-уайт-терьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (259, 'Pharaoh dog', 'Фараонова собака');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (260, 'Field Spaniel', 'Филд-спаниель');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (261, 'Bouvier des Flanders', 'Фландрский бувье');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (262, 'Fox', 'Фокстерьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (263, 'French spaniel', 'Французская болонка');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (264, 'French Bulldog', 'Французский бульдог');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (265, 'Herder', 'Хердер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (266, 'Tsverkshnautser', 'Цверкшнауцер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (267, 'Chow-chow', 'Чау-чау');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (268, 'Black and tan kunhaund', 'Черноподпалый кунхаунд');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (269, 'Chesapeake Bay Retriever', 'Чесапик-бей-ретривер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (270, 'Czech Terrier', 'Чешский терьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (271, 'Chihuahua', 'Чихуахуа');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (272, 'Chukchi sled', 'Чукотская ездовая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (273, 'Shapendus', 'Шапендус');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (274, 'Swiss Jurassic Hound', 'Швейцарская юрская гончая');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (275, 'Sheltie', 'Шелти');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (276, 'Shih Tzu', 'Ши-тцу');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (277, 'Shipperke', 'Шипперке');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (278, 'Schnauzer', 'Шнауцер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (279, 'Scottish Terrier', 'Шотландский терьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (280, 'Shtirsky Brakk', 'Штирский бракк');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (281, 'Elghund', 'Эльгхунд');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (282, 'Airedale', 'Эрдельтерьер');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (283, 'Husky', 'Эскимосская лайка');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (284, 'Eshtrelskaya Shepherd', 'Эштрельская овчарка');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (285, 'South Russian Shepherd Dog', 'Южнорусская овчарка');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (286, 'Japanese Spaniel', 'Японский спаниель');
INSERT INTO public.HB_KIND_BREED (id, breed_end, breed_ru) VALUES (287, 'Japanese Chin', 'Японский хин');